table quartiers
	lineageTag: 8c90604b-ba96-4880-b054-4d2cd758b799

	column id
		dataType: int64
		formatString: 0
		lineageTag: 3126a648-ddf3-42b8-ab0b-798e3b9339e8
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nom
		dataType: string
		lineageTag: a820af2f-e36d-4bfe-981f-4f4bb00fea8b
		summarizeBy: none
		sourceColumn: nom

		annotation SummarizationSetBy = Automatic

	column id_secteur
		dataType: int64
		formatString: 0
		lineageTag: ce29c5ff-7085-4033-9d3c-3e91386619b0
		summarizeBy: none
		sourceColumn: id_secteur

		annotation SummarizationSetBy = Automatic

	partition quartiers = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NZt62iJFGB4kZKf9MR85BwyqoglGmq-4LfTN21fTdLI"),
				    quartiers_Table = Source{[name="quartiers",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(quartiers_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"nom", type text}, {"polygon", type text}, {"id_secteur", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"polygon"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

