table Quartier
	lineageTag: 7ed0fe7a-8cdb-45a2-9589-669708679bf3

	column id
		dataType: int64
		formatString: 0
		lineageTag: 7a728da4-2db1-48e9-b05f-bde9a4da98de
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nom
		dataType: string
		lineageTag: 34e9f2d8-1108-43d9-a2e5-ea07c9f7b232
		summarizeBy: none
		sourceColumn: nom

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: ce1c03b1-addf-4b4e-a687-e700786b84d9
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 6168ea4b-57bb-43e7-8bb2-e1fc000691c9
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column id_secteur
		dataType: int64
		formatString: 0
		lineageTag: fef157e9-3547-4783-a634-4d1851079b47
		summarizeBy: none
		sourceColumn: id_secteur

		annotation SummarizationSetBy = Automatic

	partition Quartier = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NZt62iJFGB4kZKf9MR85BwyqoglGmq-4LfTN21fTdLI"),
				    Quartier_Table = Source{[name="Quartier",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Quartier_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"nom", type text}, {"latitude", type number}, {"longitude", type number}, {"id_secteur", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [latitude] <> null and [latitude] <> "")
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

