table Secteur
	lineageTag: 1f2fdd4a-3804-41b4-841e-06da125838e0

	column id
		dataType: int64
		formatString: 0
		lineageTag: 5c9503dc-e504-4539-9c5a-2ddbdab4c33b
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nom
		dataType: string
		lineageTag: 931674bd-21bb-42bf-9349-9533786c004c
		summarizeBy: none
		sourceColumn: nom

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 29e00eca-510a-483c-bcc7-ae2a6aab8f10
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 1543a983-0ed6-4ce2-96d7-7417a7238f38
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column id_ville
		dataType: int64
		formatString: 0
		lineageTag: 0a93aaba-e747-4d70-939d-f202966e2324
		summarizeBy: none
		sourceColumn: id_ville

		annotation SummarizationSetBy = Automatic

	partition Secteur = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NZt62iJFGB4kZKf9MR85BwyqoglGmq-4LfTN21fTdLI"),
				    Secteur_Table = Source{[name="Secteur",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Secteur_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"nom", type text}, {"latitude", type number}, {"longitude", type number}, {"id_ville", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

