table secteurs
	lineageTag: 5ae2e5d1-66cb-4333-9bad-78746119fac2

	column id
		dataType: int64
		formatString: 0
		lineageTag: a1735c33-9b00-43f8-bffd-a62d01a302a1
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nom
		dataType: string
		lineageTag: 4a4e3e5a-a452-4bf2-8998-86a678147552
		summarizeBy: none
		sourceColumn: nom

		annotation SummarizationSetBy = Automatic

	column id_ville
		dataType: int64
		formatString: 0
		lineageTag: e80e735c-0843-4493-89ee-9ce702800744
		summarizeBy: none
		sourceColumn: id_ville

		annotation SummarizationSetBy = Automatic

	column Column = RELATED(villes[nom]) & "-" & secteurs[nom]
		dataType: string
		lineageTag: 3f349877-badc-40a1-ae33-125139e0a76c
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition secteurs = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NZt62iJFGB4kZKf9MR85BwyqoglGmq-4LfTN21fTdLI"),
				    secteurs_Table = Source{[name="secteurs",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(secteurs_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"nom", type text}, {"id_ville", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [id_ville] <> null and [id_ville] <> "")
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

