table villes
	lineageTag: 2dbd6b27-5b90-4329-9ef1-fd01d125d561

	column id
		dataType: int64
		formatString: 0
		lineageTag: b9fd9fec-0d7a-4a9a-923b-18bd3b721919
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nom
		dataType: string
		lineageTag: 4648947c-e5e6-49d6-8bbc-df2c29f381b1
		summarizeBy: none
		sourceColumn: nom

		annotation SummarizationSetBy = Automatic

	column code_postal
		dataType: int64
		formatString: 0
		lineageTag: 4faa57b8-b281-4841-ad4d-e3b537f9983a
		summarizeBy: none
		sourceColumn: code_postal

		annotation SummarizationSetBy = Automatic

	column departement
		dataType: string
		lineageTag: 72c08e0f-4a8d-4af6-80ef-8df8113dd6e3
		summarizeBy: none
		sourceColumn: departement

		annotation SummarizationSetBy = Automatic

	partition villes = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NZt62iJFGB4kZKf9MR85BwyqoglGmq-4LfTN21fTdLI"),
				    villes_Table = Source{[name="villes",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(villes_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"nom", type text}, {"polygon", type text}, {"code_postal", Int64.Type}, {"departement", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"polygon"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

